/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MyEventsRouteImport } from './routes/my-events'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as BecomeHostRouteImport } from './routes/become-host'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as HostsHostSlugRouteImport } from './routes/hosts.$hostSlug'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as HostHostSlugMembersRouteImport } from './routes/host.$hostSlug.members'
import { Route as HostHostSlugGalleryReviewRouteImport } from './routes/host.$hostSlug.gallery-review'
import { Route as HostHostSlugDashboardRouteImport } from './routes/host.$hostSlug.dashboard'
import { Route as HostHostSlugEventsNewRouteImport } from './routes/host.$hostSlug.events.new'
import { Route as HostHostSlugEventsEventIdEditRouteImport } from './routes/host.$hostSlug.events.$eventId.edit'
import { Route as HostHostSlugEventsEventIdCheckInRouteImport } from './routes/host.$hostSlug.events.$eventId.check-in'

const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEventsRoute = MyEventsRouteImport.update({
  id: '/my-events',
  path: '/my-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeHostRoute = BecomeHostRouteImport.update({
  id: '/become-host',
  path: '/become-host',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsHostSlugRoute = HostsHostSlugRouteImport.update({
  id: '/hosts/$hostSlug',
  path: '/hosts/$hostSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HostHostSlugMembersRoute = HostHostSlugMembersRouteImport.update({
  id: '/host/$hostSlug/members',
  path: '/host/$hostSlug/members',
  getParentRoute: () => rootRouteImport,
} as any)
const HostHostSlugGalleryReviewRoute =
  HostHostSlugGalleryReviewRouteImport.update({
    id: '/host/$hostSlug/gallery-review',
    path: '/host/$hostSlug/gallery-review',
    getParentRoute: () => rootRouteImport,
  } as any)
const HostHostSlugDashboardRoute = HostHostSlugDashboardRouteImport.update({
  id: '/host/$hostSlug/dashboard',
  path: '/host/$hostSlug/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HostHostSlugEventsNewRoute = HostHostSlugEventsNewRouteImport.update({
  id: '/host/$hostSlug/events/new',
  path: '/host/$hostSlug/events/new',
  getParentRoute: () => rootRouteImport,
} as any)
const HostHostSlugEventsEventIdEditRoute =
  HostHostSlugEventsEventIdEditRouteImport.update({
    id: '/host/$hostSlug/events/$eventId/edit',
    path: '/host/$hostSlug/events/$eventId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const HostHostSlugEventsEventIdCheckInRoute =
  HostHostSlugEventsEventIdCheckInRouteImport.update({
    id: '/host/$hostSlug/events/$eventId/check-in',
    path: '/host/$hostSlug/events/$eventId/check-in',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/become-host': typeof BecomeHostRoute
  '/explore': typeof ExploreRoute
  '/my-events': typeof MyEventsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/tickets': typeof TicketsRoute
  '/events/$slug': typeof EventsSlugRoute
  '/hosts/$hostSlug': typeof HostsHostSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/host/$hostSlug/dashboard': typeof HostHostSlugDashboardRoute
  '/host/$hostSlug/gallery-review': typeof HostHostSlugGalleryReviewRoute
  '/host/$hostSlug/members': typeof HostHostSlugMembersRoute
  '/host/$hostSlug/events/new': typeof HostHostSlugEventsNewRoute
  '/host/$hostSlug/events/$eventId/check-in': typeof HostHostSlugEventsEventIdCheckInRoute
  '/host/$hostSlug/events/$eventId/edit': typeof HostHostSlugEventsEventIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/become-host': typeof BecomeHostRoute
  '/explore': typeof ExploreRoute
  '/my-events': typeof MyEventsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/tickets': typeof TicketsRoute
  '/events/$slug': typeof EventsSlugRoute
  '/hosts/$hostSlug': typeof HostsHostSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/host/$hostSlug/dashboard': typeof HostHostSlugDashboardRoute
  '/host/$hostSlug/gallery-review': typeof HostHostSlugGalleryReviewRoute
  '/host/$hostSlug/members': typeof HostHostSlugMembersRoute
  '/host/$hostSlug/events/new': typeof HostHostSlugEventsNewRoute
  '/host/$hostSlug/events/$eventId/check-in': typeof HostHostSlugEventsEventIdCheckInRoute
  '/host/$hostSlug/events/$eventId/edit': typeof HostHostSlugEventsEventIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/become-host': typeof BecomeHostRoute
  '/explore': typeof ExploreRoute
  '/my-events': typeof MyEventsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/tickets': typeof TicketsRoute
  '/events/$slug': typeof EventsSlugRoute
  '/hosts/$hostSlug': typeof HostsHostSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/host/$hostSlug/dashboard': typeof HostHostSlugDashboardRoute
  '/host/$hostSlug/gallery-review': typeof HostHostSlugGalleryReviewRoute
  '/host/$hostSlug/members': typeof HostHostSlugMembersRoute
  '/host/$hostSlug/events/new': typeof HostHostSlugEventsNewRoute
  '/host/$hostSlug/events/$eventId/check-in': typeof HostHostSlugEventsEventIdCheckInRoute
  '/host/$hostSlug/events/$eventId/edit': typeof HostHostSlugEventsEventIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/become-host'
    | '/explore'
    | '/my-events'
    | '/reset-password'
    | '/signin'
    | '/tickets'
    | '/events/$slug'
    | '/hosts/$hostSlug'
    | '/invite/$token'
    | '/host/$hostSlug/dashboard'
    | '/host/$hostSlug/gallery-review'
    | '/host/$hostSlug/members'
    | '/host/$hostSlug/events/new'
    | '/host/$hostSlug/events/$eventId/check-in'
    | '/host/$hostSlug/events/$eventId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/become-host'
    | '/explore'
    | '/my-events'
    | '/reset-password'
    | '/signin'
    | '/tickets'
    | '/events/$slug'
    | '/hosts/$hostSlug'
    | '/invite/$token'
    | '/host/$hostSlug/dashboard'
    | '/host/$hostSlug/gallery-review'
    | '/host/$hostSlug/members'
    | '/host/$hostSlug/events/new'
    | '/host/$hostSlug/events/$eventId/check-in'
    | '/host/$hostSlug/events/$eventId/edit'
  id:
    | '__root__'
    | '/'
    | '/become-host'
    | '/explore'
    | '/my-events'
    | '/reset-password'
    | '/signin'
    | '/tickets'
    | '/events/$slug'
    | '/hosts/$hostSlug'
    | '/invite/$token'
    | '/host/$hostSlug/dashboard'
    | '/host/$hostSlug/gallery-review'
    | '/host/$hostSlug/members'
    | '/host/$hostSlug/events/new'
    | '/host/$hostSlug/events/$eventId/check-in'
    | '/host/$hostSlug/events/$eventId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BecomeHostRoute: typeof BecomeHostRoute
  ExploreRoute: typeof ExploreRoute
  MyEventsRoute: typeof MyEventsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SigninRoute: typeof SigninRoute
  TicketsRoute: typeof TicketsRoute
  EventsSlugRoute: typeof EventsSlugRoute
  HostsHostSlugRoute: typeof HostsHostSlugRoute
  InviteTokenRoute: typeof InviteTokenRoute
  HostHostSlugDashboardRoute: typeof HostHostSlugDashboardRoute
  HostHostSlugGalleryReviewRoute: typeof HostHostSlugGalleryReviewRoute
  HostHostSlugMembersRoute: typeof HostHostSlugMembersRoute
  HostHostSlugEventsNewRoute: typeof HostHostSlugEventsNewRoute
  HostHostSlugEventsEventIdCheckInRoute: typeof HostHostSlugEventsEventIdCheckInRoute
  HostHostSlugEventsEventIdEditRoute: typeof HostHostSlugEventsEventIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-events': {
      id: '/my-events'
      path: '/my-events'
      fullPath: '/my-events'
      preLoaderRoute: typeof MyEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-host': {
      id: '/become-host'
      path: '/become-host'
      fullPath: '/become-host'
      preLoaderRoute: typeof BecomeHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/$hostSlug': {
      id: '/hosts/$hostSlug'
      path: '/hosts/$hostSlug'
      fullPath: '/hosts/$hostSlug'
      preLoaderRoute: typeof HostsHostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/$hostSlug/members': {
      id: '/host/$hostSlug/members'
      path: '/host/$hostSlug/members'
      fullPath: '/host/$hostSlug/members'
      preLoaderRoute: typeof HostHostSlugMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/$hostSlug/gallery-review': {
      id: '/host/$hostSlug/gallery-review'
      path: '/host/$hostSlug/gallery-review'
      fullPath: '/host/$hostSlug/gallery-review'
      preLoaderRoute: typeof HostHostSlugGalleryReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/$hostSlug/dashboard': {
      id: '/host/$hostSlug/dashboard'
      path: '/host/$hostSlug/dashboard'
      fullPath: '/host/$hostSlug/dashboard'
      preLoaderRoute: typeof HostHostSlugDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/$hostSlug/events/new': {
      id: '/host/$hostSlug/events/new'
      path: '/host/$hostSlug/events/new'
      fullPath: '/host/$hostSlug/events/new'
      preLoaderRoute: typeof HostHostSlugEventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/$hostSlug/events/$eventId/edit': {
      id: '/host/$hostSlug/events/$eventId/edit'
      path: '/host/$hostSlug/events/$eventId/edit'
      fullPath: '/host/$hostSlug/events/$eventId/edit'
      preLoaderRoute: typeof HostHostSlugEventsEventIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/$hostSlug/events/$eventId/check-in': {
      id: '/host/$hostSlug/events/$eventId/check-in'
      path: '/host/$hostSlug/events/$eventId/check-in'
      fullPath: '/host/$hostSlug/events/$eventId/check-in'
      preLoaderRoute: typeof HostHostSlugEventsEventIdCheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BecomeHostRoute: BecomeHostRoute,
  ExploreRoute: ExploreRoute,
  MyEventsRoute: MyEventsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SigninRoute: SigninRoute,
  TicketsRoute: TicketsRoute,
  EventsSlugRoute: EventsSlugRoute,
  HostsHostSlugRoute: HostsHostSlugRoute,
  InviteTokenRoute: InviteTokenRoute,
  HostHostSlugDashboardRoute: HostHostSlugDashboardRoute,
  HostHostSlugGalleryReviewRoute: HostHostSlugGalleryReviewRoute,
  HostHostSlugMembersRoute: HostHostSlugMembersRoute,
  HostHostSlugEventsNewRoute: HostHostSlugEventsNewRoute,
  HostHostSlugEventsEventIdCheckInRoute: HostHostSlugEventsEventIdCheckInRoute,
  HostHostSlugEventsEventIdEditRoute: HostHostSlugEventsEventIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
